logging:
  level:
    root: info
server:
  port: 8081
spring:
  cloud:
    gcp:
      pubsub:
        enabled: true
        credentials:
          location: file:/home/krungthai-dg-lending-pubsub.json