logging:
  level:
    root: info
server:
  port: 8081

spring:
  cloud:
    gcp:
      pubsub:
        project-id: poc-hiperledger
        credentials:
          location: file:/Users/pigke/IdeaProjects/spring-echo/GCP-PubSub/simplePubSub/src/main/resources/poc-hiperledger-002c0d988c4d.json
