logging:
  level:
    root: info
spring:
  webservices:
    path: /demo
server:
  port: 8080

gcp:
  project-2:
    topic: sample.response
    subscription: sample.response.subscription
    project-id: krungthai-dg-lending-sit
    credentialpath: /Users/pigke/Documents/github-demo/pubsubDemo/src/main/resources/krungthai-dg-lending-sit.json
  project-1:
    topic: uat.stream.loan-creditscoring.submission
    subscription: uat.stream.loan-creditscoring.submission.subscription2
    project-id: krungthai-dg-lending-sit
    credentialpath: /Users/pigke/Documents/github-demo/pubsubDemo/src/main/resources/krungthai-dg-lending-sit.json