server:
  port: 8080

servlet:
  context-path: /test

logging:
  level:
    root: info

redis:
  redis-demo-one:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 2
        max-wait: -1
  redis-demo-two:
    host: localhost
    port: 6380
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 2
        max-wait: -1